import RegisterForm from '@/components/modules/auth/register/RegisterForm';
import React from 'react';
import styles from './Register.module.css'

export const metadata = {
    title: 'Contact',
    description: 'Generated by create next app',
}

const RegisterPage = () => {
    return (
        <div className={styles.registerContainer }>
            <RegisterForm />
        </div>
    );
};

export default RegisterPage
